# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Copmany Save Job

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :batch:batch-company-save:bootJar
      - name: Commpany Save Job Execute
        run: java -jar -Dspring.profiles.active=test -Dspring.batch.job.names=companySaveJob ./batch/batch-company-save/build/libs/batch-company-save-0.0.1-SNAPSHOT.jar -marketType=KOSDAQ
      - name: action-slack
        uses: 8398a7/action-slack@v3.0.2
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}